
// This file has been generated by the GUI designer. Do not modify.
namespace Translators
{
	public partial class RootWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.FileChooserButton FileChooser;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button button2;
		private global::Gtk.Button button3;
		private global::Gtk.Button button1;
		private global::Gtk.ProgressBar CompileProgressBar;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView ConsoleTextView;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Translators.RootWindow
			this.Name = "Translators.RootWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Bodnya Alexey's Translator. Group TV-11.");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Translators.Resources.Icons.Puzzle-grey.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 640;
			this.DefaultHeight = 480;
			// Container child Translators.RootWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.FileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Оберіть файл"), ((global::Gtk.FileChooserAction)(0)));
			this.FileChooser.Name = "FileChooser";
			this.hbox1.Add (this.FileChooser);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.FileChooser]));
			w1.Position = 0;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			// Container child button2.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Compile");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.button2.Add (w3);
			this.hbox2.Add (this.button2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			// Container child button3.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_dialog-info", global::Gtk.IconSize.Menu);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.LabelProp = global::Mono.Unix.Catalog.GetString ("Info");
			w16.UseUnderline = true;
			w13.Add (w16);
			w12.Add (w13);
			this.button3.Add (w12);
			this.hbox2.Add (this.button3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button3]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			// Container child button1.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Poliz");
			w25.UseUnderline = true;
			w22.Add (w25);
			w21.Add (w22);
			this.button1.Add (w21);
			this.hbox2.Add (this.button1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button1]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.CompileProgressBar = new global::Gtk.ProgressBar ();
			this.CompileProgressBar.Name = "CompileProgressBar";
			this.hbox2.Add (this.CompileProgressBar);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.CompileProgressBar]));
			w30.Position = 3;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ConsoleTextView = new global::Gtk.TextView ();
			this.ConsoleTextView.CanFocus = true;
			this.ConsoleTextView.Name = "ConsoleTextView";
			this.GtkScrolledWindow.Add (this.ConsoleTextView);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w33.PackType = ((global::Gtk.PackType)(1));
			w33.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.FileChooser.SelectionChanged += new global::System.EventHandler (this.OpenFileEventHandler);
			this.button2.Clicked += new global::System.EventHandler (this.CompileFileEventHandler);
			this.button3.Clicked += new global::System.EventHandler (this.TableButtonHandler);
			this.button1.Clicked += new global::System.EventHandler (this.PolizButtonHandler);
		}
	}
}
