
// This file has been generated by the GUI designer. Do not modify.
namespace Translators
{
	public partial class RootWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.FileChooserButton FileChooser;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button button2;
		private global::Gtk.Button button3;
		private global::Gtk.ProgressBar CompileProgressBar;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView ConsoleTextView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Translators.RootWindow
			this.Name = "Translators.RootWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Bodnya Alexey's Translator. Group TV-11.");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Translators.Resources.Icons.Puzzle-grey.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 640;
			this.DefaultHeight = 480;
			// Container child Translators.RootWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.FileChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
			this.FileChooser.Name = "FileChooser";
			this.hbox1.Add (this.FileChooser);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.FileChooser]));
			w1.Position = 0;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Compile");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			this.button2.Image = w3;
			this.hbox2.Add (this.button2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Info");
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_dialog-info", global::Gtk.IconSize.Menu);
			this.button3.Image = w5;
			this.hbox2.Add (this.button3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.CompileProgressBar = new global::Gtk.ProgressBar ();
			this.CompileProgressBar.Name = "CompileProgressBar";
			this.hbox2.Add (this.CompileProgressBar);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.CompileProgressBar]));
			w7.Position = 2;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ConsoleTextView = new global::Gtk.TextView ();
			this.ConsoleTextView.CanFocus = true;
			this.ConsoleTextView.Name = "ConsoleTextView";
			this.ConsoleTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.ConsoleTextView);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.FileChooser.SelectionChanged += new global::System.EventHandler (this.OpenFileEventHandler);
			this.button2.Clicked += new global::System.EventHandler (this.CompileFileEventHandler);
			this.button3.Clicked += new global::System.EventHandler (this.TableButtonHandler);
		}
	}
}
