
// This file has been generated by the GUI designer. Do not modify.
namespace Translators
{
	public partial class MainWindow
	{
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button OpenButton;
		private global::Gtk.Button SaveButton;
		private global::Gtk.Button SaveAsButton;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.Button CompileButton;
		private global::Gtk.ProgressBar CompileProgressBar;
		private global::Gtk.Button ShowLexemTableButton;
		private global::Gtk.Button ShowGrammarButton;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.VPaned vpaned2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView CodeTextView;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TextView ConsoleTextView;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Translators.MainWindow
			this.Name = "Translators.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("IDE Translator by Bodnya Alexey TV-11");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Container child Translators.MainWindow.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.OpenButton = new global::Gtk.Button ();
			this.OpenButton.CanFocus = true;
			this.OpenButton.Name = "OpenButton";
			this.OpenButton.UseUnderline = true;
			this.OpenButton.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Translators.Lab01.Resources.Images.OpenFile.png");
			this.OpenButton.Image = w1;
			this.hbox3.Add (this.OpenButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.OpenButton]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.SaveButton = new global::Gtk.Button ();
			this.SaveButton.CanFocus = true;
			this.SaveButton.Name = "SaveButton";
			this.SaveButton.UseUnderline = true;
			this.SaveButton.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Translators.Lab01.Resources.Images.Save.png");
			this.SaveButton.Image = w3;
			this.hbox3.Add (this.SaveButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.SaveButton]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.SaveAsButton = new global::Gtk.Button ();
			this.SaveAsButton.CanFocus = true;
			this.SaveAsButton.Name = "SaveAsButton";
			this.SaveAsButton.UseUnderline = true;
			this.SaveAsButton.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Translators.Lab01.Resources.Images.SaveAs.png");
			this.SaveAsButton.Image = w5;
			this.hbox3.Add (this.SaveAsButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.SaveAsButton]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox3.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vseparator1]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.CompileButton = new global::Gtk.Button ();
			this.CompileButton.CanFocus = true;
			this.CompileButton.Name = "CompileButton";
			this.CompileButton.UseUnderline = true;
			this.CompileButton.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Translators.Lab01.Resources.Images.Compile.png");
			this.CompileButton.Image = w8;
			this.hbox3.Add (this.CompileButton);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.CompileButton]));
			w9.Position = 4;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.CompileProgressBar = new global::Gtk.ProgressBar ();
			this.CompileProgressBar.Name = "CompileProgressBar";
			this.hbox3.Add (this.CompileProgressBar);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.CompileProgressBar]));
			w10.Position = 5;
			// Container child hbox3.Gtk.Box+BoxChild
			this.ShowLexemTableButton = new global::Gtk.Button ();
			this.ShowLexemTableButton.CanFocus = true;
			this.ShowLexemTableButton.Name = "ShowLexemTableButton";
			this.ShowLexemTableButton.UseUnderline = true;
			this.ShowLexemTableButton.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Translators.Lab01.Resources.Images.Table.png");
			this.ShowLexemTableButton.Image = w11;
			this.hbox3.Add (this.ShowLexemTableButton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.ShowLexemTableButton]));
			w12.Position = 6;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.ShowGrammarButton = new global::Gtk.Button ();
			this.ShowGrammarButton.CanFocus = true;
			this.ShowGrammarButton.Name = "ShowGrammarButton";
			this.ShowGrammarButton.UseUnderline = true;
			this.ShowGrammarButton.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Translators.Lab01.Resources.Images.Help.png");
			this.ShowGrammarButton.Image = w13;
			this.hbox3.Add (this.ShowGrammarButton);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.ShowGrammarButton]));
			w14.Position = 7;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 1;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 347;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.CodeTextView = new global::Gtk.TextView ();
			this.CodeTextView.CanFocus = true;
			this.CodeTextView.Name = "CodeTextView";
			this.CodeTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.CodeTextView.LeftMargin = 5;
			this.GtkScrolledWindow.Add (this.CodeTextView);
			this.vpaned2.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w17 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.GtkScrolledWindow]));
			w17.Resize = false;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow1.WindowPlacement = ((global::Gtk.CornerType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.ConsoleTextView = new global::Gtk.TextView ();
			this.ConsoleTextView.CanFocus = true;
			this.ConsoleTextView.Name = "ConsoleTextView";
			this.ConsoleTextView.Editable = false;
			this.ConsoleTextView.WrapMode = ((global::Gtk.WrapMode)(2));
			this.ConsoleTextView.LeftMargin = 5;
			this.GtkScrolledWindow1.Add (this.ConsoleTextView);
			this.vpaned2.Add (this.GtkScrolledWindow1);
			global::Gtk.Paned.PanedChild w19 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.GtkScrolledWindow1]));
			w19.Resize = false;
			this.vpaned1.Add (this.vpaned2);
			this.vbox3.Add (this.vpaned1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vpaned1]));
			w21.Position = 1;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w22.Position = 0;
			this.Add (this.hbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 664;
			this.DefaultHeight = 455;
			this.Show ();
			this.OpenButton.Clicked += new global::System.EventHandler (this.OpenFileEventHandler);
			this.SaveButton.Clicked += new global::System.EventHandler (this.SaveButtonEventHandler);
			this.CompileButton.Clicked += new global::System.EventHandler (this.CompileFileEventHandler);
			this.ShowLexemTableButton.Clicked += new global::System.EventHandler (this.TableButtonHandler);
		}
	}
}
